setParamプラグイン向けの機能を追加 (otoini.py, utils)
oatsu-gh/utaupy pull request #13
Opened 2024-10-03 10:18 UTC by 8uta

## 変更内容の概要

- `otoini.py`に、setParamプラグイン向けの関数とメソッドを追加しました。
- `utils`に、トライ木を扱う`_trie.py`を追加しました。
- それに伴い、`utils`の`__init__.py`を更新しました。

## 変更の理由

setParamプラグインの制作を容易にするためです。

## 影響範囲

この変更により、`otoini.py`または`utils`を使用しているコードが影響を受ける可能性があります。

## テスト結果

- 関数およびメソッド単位で、VS Code上でスクリプトをテストし、正常に動作することを確認しました。
- Nuitkaを用いてexe化し、setParam上での動作を確認しました。

## レビュワーへの注意点

- 可能な限り確認を行いましたが、入門から日が浅く、初めてのプルリクエストですので、初歩的なミスが含まれている可能性があります。
- 他のコードに悪影響を及ぼさないか、書き方が適切かどうか、特にご確認をお願いします。

## 変更の詳細

### 関数

`otoini.py`に、次の関数を追加しました。

- `read_in_param`: この関数は、次の情報を受け取ります。
  - `cur_dir`: setParamプラグイン本体が入っているフォルダの絶対パス。
  - `vb_dir`: setParamで開いている音源フォルダ、または処理対象の音源フォルダの絶対パス。
  - `oto_ini_path`: 原音設定の絶対パス。
  - `oto_sp_path`: 更新用原音設定の絶対パス。
  - `f0_interval`: F0の抽出間隔(単位=秒)。
  - `power_interval`: パワーの抽出間隔(単位=秒)。
  - `view_rows`: setParamの波形窓で現在表示しているデータの行番号。
  - `select_rows`: setParamのパラメータ一覧表で現在選択しているセルの行番号。
  - `comment_txt_path`: setParam用コメントテキストの絶対パス。
  - `comment_sp_path`: setParam用の更新用コメントテキストの絶対パス。
- `load_sp`: この関数は、setParamプラグインの汎用的な初期設定を行います。
- `create_cv_dict`: この関数は、単独音パラメータの辞書を作成します。

#### メソッド

`otoini.py`の`OtoIni`クラスに、次のメソッドを追加しました。

- `_apply_regex`: このメソッドは、対象行 (エイリアスが正規表現に一致した行、または全行) に、引数で渡された関数を適用します。
- `replace_regexp_alias`: このメソッドは、エイリアスを置換します。(正規表現対応)
- `add_alias`: このメソッドは、エイリアスに接頭辞または接尾辞を追加します。
- `trim_alias`: このメソッドは、エイリアスの前後から文字数を指定して削除します。
- `remove_duplicate`: このメソッドは、エイリアスが重複している行を削除します。
- `copy_rename`: このメソッドは、行の複製とリネームを行います。
- `copy_rename_csv`: このメソッドは、「before,after」というcsv形式で書かれたファイルを元に、`copy_rename`を実行します。
- `round_param`: このメソッドは、指定した小数点以下の桁数で四捨五入を行います。
- `overlap_1_3`: このメソッドは、オーバーラップを先行発声の1/3にし、先行発声、固定範囲、右ブランクの位置は動かしません。
- `convert_vcv`: このメソッドは、収録BPMから求めた連続音パラメータに変換します。
- `convert_cv`: このメソッドは、収録BPMと辞書から求めた単独音パラメータに変換します。
- `set_cv_vcv`: このメソッドは、単独音パラメータと連続音パラメータを適用します。

#### プライベートスクリプト

`utils`に`_trie_dict.py`を追加しました。これはトライ木を作成および検索するためのモジュールです。現在は単独音の辞書を作成する`create_cv_dict`とその検索にのみ使用していますが、新しい内容も辞書化できるようにしています。

2024-10-04 05:45 UTC, oatsu-gh commented on utaupy/otoini.py
> +    def round_param(self, digits=None, pattern=None):
数値をroundするのは明白なのでメソッド名 `round()` でやってしまいましょう！

2024-10-04 05:46 UTC, oatsu-gh commented on utaupy/otoini.py
> +    def overlap_1_3(self, value=None, fixed=None, pattern=None):
汎用性に欠けるとはいえよく使う機能だと思うので、取り入れようと思います。
関数名このままにするか変更するか検討中です。

2024-10-04 05:56 UTC, 8uta commented on utaupy/otoini.py
> +    def round_param(self, digits=None, pattern=None):
ありがとうございます。その件でひとつ心配していて、私の環境ではメソッドを呼び出すとき文字色が白なんですが、round()にすると、文字色が緑になります。これはn = round(n, 3)のように四捨五入するときと同じ色です。これは大丈夫でしょうか？

2024-10-04 07:08 UTC, oatsu-gh requested changes
- otoini.OtoIni の汎用的なメソッドについては取り込みたいと思います。関数名等の調整をお願いします。
- 具体的な数値固定の処理を伴うものはできるだけ避けたいので、その関連は見送りとしたいです。
setParam プラグインの入出力はぜひとも使用したいです。その関連関数については otoini.py ではなくsetparam.py として新ファイルでお願いします。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        return self._apply_regex(overlap_1_3_func, pattern=pattern)
value と fixed の組み合わせで分岐するのは使い方を覚えづらいため、
`value` -> `bpm=120`
`fixed` -> `preutterance=None`
のようなオプション引数にするのが良いと考えます。
preutterance が None でなければ先行発声に基づいて処理、そうでなければbpmで計算するという流れがいいかなと思いました。

先行発声に対するオーバーラップの比率については、オプション引数 ratio (デフォルト値 1/3) を追加して、1/2 等任意の比率で実行にできるようにしたら汎用性上がりそうです。1/3 固定ではなくなるので関数名はかえた方がいいかもしれないです。init_overlap_ratio とかでしょうか、、、。

上記をまとめると、`def overlap_1_3(self, bpm=120, preutterance=None, ratio=1/3, pattern=None)` のような形式がいいかと思います。実装意図と異なる部分あったらコメントください。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +    def round_param(self, digits=None, pattern=None):
関数定義だと組み込み関数の round をオーバーライドしてしまうのでNGですが、OtoIni 内のメソッドであれば許容されます。色はおそらく、組み込み関数を使う際に分かりやすいようにテーマが気を利かせてくれているのだと思います。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +    def convert_vcv(self, bpm=None, pattern=None):
```python
def convert_vcv(self, bpm=120, pattern=None):
```
とすれば 後続の `bpm = float(bpm or 120)` を省略可能です。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +    def convert_cv(self, bpm=None, pattern=None):
```python
def convert_cv(self, bpm=120, pattern=None):
```
とすれば 後続の `bpm = float(bpm or 120)` を省略可能です。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        self.data = unique_otoini
- 必須機能だと思うので大変助かります。
- メソッド名は pandas に倣って、`drop_duplicates` にしたいと思います。
- 残すのを最初の行にするか最後の行にするかを選べるといいなと思います。
  - オプション引数 `keep='first'` を追加し、'first' の時は最初の行を残して、'last' の時は最後の行を残し、それ以外が入力されたときはエラー
  - last の場合の実装は、listを反転させて処理したのちに再度反転させれば簡単だと思います。(別の方法でもかまいません)

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        return self
便利そうなので隠匿なしで `apply_regex` または `apply` として追加してしまっていいと思います。
また、もし余裕があれば、for ループの代わりに内包表記か map を使うと高速化できそうです。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        return self
連続音の先頭を単独音化したり、「を」がないとき「お」から複製したりする用途を意図されたのかと存じます。便利ではあるのですが、内容的にユーザー側の実装でよい気がするので見送りの方針とさせていただきます。
また、for 分の中身の部分ですが、
```python
from copy import deepcopy

...
        for oto in self:
            if before_regex.fullmatch(oto.alias) and not any(
                after_regex.fullmatch(oto_after.alias) for oto_after in self
            ):
                new_oto = deepcopy(oto)
                new_oto.alias = after
                self.append(new_oto)
                break
        return self
```

とすると簡潔です。

また、before に一致するエイリアスが複数行ある場合でも、最初に一致したもので処理されることをメソッドのコメントに書いておいた方が良さそうです。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        return self
パラメータの初期値を登録するメソッドですね。

原音設定パラメータを登録していくという観点では重要な機能ではあるのですが、数値の決め方が好みに依存してしまうので取り扱いが悩ましいです。具体的な数値の設定を含むような処理は個々のプラグイン製作者で決めてもらうほうがいいかなと思いますので、今回は適用見送りとさせていただきます。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +
convert_cv, convert_vcv, set_cv_vcv 見送りに伴って見送りとします。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/utils/__init__.py
convert_cv, convert_vcv, set_cv_vcv 見送りに伴って見送りとします。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/utils/_trie.py
otoini.Oto.convert_cv, convert_vcv, set_cv_vcv 見送りに伴って見送りとします。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +
これすごく助かります！
setParam プラグインに特化した setparam.py として別ファイルで作成お願いします。

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +    settings = {}
この行は不要

2024-10-04 07:08 UTC, oatsu-gh commented on utaupy/otoini.py
> +        return self._apply_regex(trim_func, pattern=pattern)
取り扱い検討中です。ライブラリとしては無くてもいい気もする一方であってもいい気もします。
いったん見送りとしますが今後継続検討としたく、切り分けてプルリク出していただけると幸いです。

2024-10-05 00:30 UTC, 8uta commented
たくさんのご指摘ありがとうございます…！一旦こちらで整理してみて、疑問点をまとめて改めてお伺いします。

2024-10-05 00:44 UTC, 8uta commented on utaupy/otoini.py
> +    settings = {}
すみません、こちらだと4行くらい表示されているので…何行目のことを指していますか？ settings=のことのみでしょうか。それとも、コメントを編集するパスも取得しなくて良いという意味でしょうか？

2024-10-05 01:58 UTC, oatsu-gh commented on utaupy/otoini.py
> +    settings = {}
失礼しました。settingの行だけです。
つぎの行以降で定義し直しているので、この行はなくていいと思いました。

2024-10-05 02:56 UTC, 8uta commented on utaupy/otoini.py
> +
ありがとうございます。関数名は変更しますか？

2024-10-05 06:43 UTC, oatsu-gh commented on utaupy/otoini.py
> +
read_in_param → read_inparam
load_sp → load
でお願いします。

2024-10-10 05:58 UTC, 8uta commented
# 修正内容

レビューありがとうございました。コードを修正しましたのでご確認ください。

## 変更点

- 次の機能を削除しました。
  - `_trie.py`
  - `copy_rename`
  - `copy_rename_csv`
  - `convert_cv`
  - `convert_vcv`
  - `set_cv_vcv`
  - `create_cv_dict`

- 次の機能を別プルリクエストに移動する予定です。
  - `replace_regexp_alias`
  - `add_alias`
  - `trim_alias`

- 次の変更を行いました。
  - `utaupy\utils\__init__.py`: 初期化
  - `utaupy\setparam.py`: 新規作成
  - `utaupy\__init__.py`: setParamを追加
  - `utaupy\otoini.py`:
    - `read_in_param`: `read_inparam`に改名、`setparam.py`に移動、`setting={}`の行を削除
    - `load_sp`: `load`に改名、`setparam.py`に移動
    - `_apply_regex`: `apply_regex`に改名、mapなどを追加
    - `remove_duplicate`: `drop_duplicates`に改名、最後の行を残せるように変更
    - `overlap_1_3`:
      - 定義を `init_overlap_ratio(self, bpm=120, preutterance=None, ratio=1/3, pattern=None)` に変更
      - 計算式を `new_overlap = new_preutterance * ratio` に変更

2024-10-10 08:58 UTC, 8uta commented
エイリアス関連の機能を、別プルリクエスト #14 に分割しました。

2024-10-10 11:19 UTC, oatsu-gh commented
ありがとうございます。内容確認しました。

2024-10-10 11:21 UTC, merged